### ISSUE TITLE
Undocumented behaviour of API parameters.

### ISSUE THREAD

**Issue by yasiupl** [hspsh/whohacks#39]
This query should return users in the space 365 days ago, but instead it returns all users and unknown devices from the past 365 days.
https://whois.at.hs3.pl/api/now?days=365

Same applies to 'hours' and 'minutes' parameters.

**Comment by yasiupl** [comment]
Is it the intended behavior?

**Comment by not7cd** [comment]
yes, this is intended behavior

**Comment by allgreed** [comment]
@not7cd Ale po co to, na co to i czy gdzieś dokumentujemy?

**Comment by LiquidLemon** [comment]
Documenting the API isn't a priority and this will be obsoleted by #56.
