### ISSUE TITLE
Move to new mikrotik script - add IP to database

### ISSUE THREAD

**Issue by cr1tbit** [hspsh/whohacks#53]
The new mikrotik outputs the assigned IP which is nice.

I use whois to assert the network state quite often.

It's a pretty easy fix.

- [ ] move to new  mikrotik script (backwards-compatible)
- [ ] add IP to DB schema
- [ ] add IP to overview table
- [ ] handle static IPs (they're somehow different in the output JSON from mikrotik)

**Comment by LiquidLemon** [comment]
Will implement once all the logic is in Python (see #55)
